<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class OpdSeeder extends Seeder
{
    public function run(): void
    {
        if (!Schema::hasTable('opd')) {
            $this->command->warn('Table opd tidak ada. Jalankan migration dulu.');
            return;
        }

        $opds = [
            ['nama' => 'BADAN KEPEGAWAIAN DAN PENGEMBANGAN SUMBER DAYA MANUSIA KOTA SAMARINDA', 'singkatan' => 'BKPPD', 'is_active' => true],
            ['nama' => 'BADAN KESATUAN BANGSA DAN POLITIK', 'singkatan' => 'KESBANGPOL', 'is_active' => true],
            ['nama' => 'BADAN KESATUAN BANGSA DAN POLITIK KOTA SAMARINDA', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'BADAN PENANGGULANGAN BENCANA DAERAH', 'singkatan' => 'BBPBD', 'is_active' => true],
            ['nama' => 'BADAN PENDAPATAN DAERAH', 'singkatan' => 'BAPENDA', 'is_active' => true],
            ['nama' => 'BADAN PENELITIAN DAN PENGEMBANGAN', 'singkatan' => 'LITBANG', 'is_active' => true],
            ['nama' => 'BADAN PENGELOLAAN KEUANGAN DAN ASET DAERAH', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'BADAN PERENCANAAN PEMBANGUNAN, RISET DAN INOVASI DAERAH', 'singkatan' => 'BAPPEDA', 'is_active' => true],
            ['nama' => 'DEWAN PERWAKILAN RAKYAT DAERAH', 'singkatan' => 'DPRD', 'is_active' => true],
            ['nama' => 'DINAS KEARSIPAN', 'singkatan' => 'ARSIP', 'is_active' => true],
            ['nama' => 'DINAS KEBUDAYAAN', 'singkatan' => 'DISBUD', 'is_active' => true],
            ['nama' => 'DINAS KEPENDUDUKAN DAN PENCATATAN SIPIL', 'singkatan' => 'DISDUKCAPIL', 'is_active' => true],
            ['nama' => 'DINAS KESEHATAN', 'singkatan' => 'DINKES', 'is_active' => true],
            ['nama' => 'DINAS KETAHANAN PANGAN', 'singkatan' => 'DKP', 'is_active' => true],
            ['nama' => 'DINAS KETAHANAN PANGAN DAN PERTANIAN', 'singkatan' => 'PERTANIAN', 'is_active' => true],
            ['nama' => 'DINAS KOMUNIKASI DAN INFORMATIKA', 'singkatan' => 'DISKOMINFO', 'is_active' => true],
            ['nama' => 'DINAS KOPERASI , USAHA KECIL MENENGAH DAN PERINDUSTRIAN', 'singkatan' => 'KOPUKM', 'is_active' => true],
            ['nama' => 'DINAS LINGKUNGAN HIDUP', 'singkatan' => 'DLH', 'is_active' => true],
            ['nama' => 'DINAS PARIWISATA', 'singkatan' => 'DISPAR', 'is_active' => true],
            ['nama' => 'DINAS PEKERJAAN UMUM DAN PENATAAN RUANG', 'singkatan' => 'PUPR', 'is_active' => true],
            ['nama' => 'DINAS PEMADAM KEBAKARAN DAN PENYELAMATAN KOTA SAMARINDA', 'singkatan' => 'DAMKAR', 'is_active' => true],
            ['nama' => 'DINAS PEMBERDAYAAN PEREMPUAN DAN PERLINDUNGAN ANAK', 'singkatan' => 'DP3A', 'is_active' => true],
            ['nama' => 'DINAS PEMUDA, OLAHRAGA DAN PARIWISATA', 'singkatan' => 'DISPORA', 'is_active' => true],
            ['nama' => 'DINAS PENANAMAN MODAL DAN PELAYANAN TERPADU SATU PINTU', 'singkatan' => 'DPMPTSP', 'is_active' => true],
            ['nama' => 'DINAS PENDIDIKAN DAN KEBUDAYAAN', 'singkatan' => 'DISDIK', 'is_active' => true],
            ['nama' => 'DINAS PENGENDALIAN PENDUDUK DAN KELUARGA BERENCANA', 'singkatan' => 'DALDUK', 'is_active' => true],
            ['nama' => 'DINAS PERDAGANGAN', 'singkatan' => 'DISDAG', 'is_active' => true],
            ['nama' => 'DINAS PERHUBUNGAN', 'singkatan' => 'DISHUB', 'is_active' => true],
            ['nama' => 'DINAS PERIKANAN', 'singkatan' => 'PERIKANAN', 'is_active' => true],
            ['nama' => 'DINAS PERINDUSTRIAN', 'singkatan' => 'DISPERIN', 'is_active' => true],
            ['nama' => 'DINAS PERPUSTAKAAN DAN KEARSIPAN', 'singkatan' => 'PERPUS', 'is_active' => true],
            ['nama' => 'DINAS PERTANAHAN', 'singkatan' => 'PERTANAHAN', 'is_active' => true],
            ['nama' => 'DINAS PERUMAHAN DAN KAWASAN PERMUKIMAN', 'singkatan' => 'PERKIM', 'is_active' => true],
            ['nama' => 'DINAS SOSIAL DAN PEMBERDAYAAN MASYARAKAT', 'singkatan' => 'DINSOS', 'is_active' => true],
            ['nama' => 'DINAS TENAGA KERJA', 'singkatan' => 'DISNAKER', 'is_active' => true],
            ['nama' => 'INSPEKTORAT DAERAH KOTA SAMARINDA', 'singkatan' => 'INSPEKTORAT', 'is_active' => true],
            ['nama' => 'KECAMATAN LOA JANAN ILIR', 'singkatan' => 'KEC-LJI', 'is_active' => true],
            ['nama' => 'KECAMATAN PALARAN', 'singkatan' => 'KEC-PALARAN', 'is_active' => true],
            ['nama' => 'KECAMATAN SAMARINDA ILIR', 'singkatan' => 'KEC-SMR-ILIR', 'is_active' => true],
            ['nama' => 'KECAMATAN SAMARINDA KOTA', 'singkatan' => 'KEC-SMR-KOTA', 'is_active' => true],
            ['nama' => 'KECAMATAN SAMARINDA SEBERANG', 'singkatan' => 'KEC-SMR-SEBERANG', 'is_active' => true],
            ['nama' => 'KECAMATAN SAMARINDA ULU', 'singkatan' => 'KEC-SMR-ULU', 'is_active' => true],
            ['nama' => 'KECAMATAN SAMARINDA UTARA', 'singkatan' => 'KEC-SMR-UTARA', 'is_active' => true],
            ['nama' => 'KECAMATAN SAMBUTAN', 'singkatan' => 'KEC-SAMBUTAN', 'is_active' => true],
            ['nama' => 'KECAMATAN SUNGAI KUNJANG', 'singkatan' => 'KEC-SEI-KUNJANG', 'is_active' => true],
            ['nama' => 'KECAMATAN SUNGAI PINANG', 'singkatan' => 'KEC-SEI-PINANG', 'is_active' => true],
            ['nama' => 'KELURAHAN AIR HITAM', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'KELURAHAN AIR PUTIH', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'KELURAHAN BANDARA', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'KELURAHAN BANTUAS', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'KELURAHAN BAQA', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'KELURAHAN BUDAYA PAMPANG', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'KELURAHAN BUGIS', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'KELURAHAN BUKUAN', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'KELURAHAN DADI MULYA', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'KELURAHAN GUNUNG KELUA', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'KELURAHAN GUNUNG LINGAI', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'KELURAHAN GUNUNG PANJANG', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'KELURAHAN HANDIL BAKTI', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'KELURAHAN HARAPAN BARU', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'KELURAHAN JAWA', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'KELURAHAN KARANG ANYAR', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'KELURAHAN KARANG ASAM ILIR', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'KELURAHAN KARANG ASAM ULU', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'KELURAHAN KARANG MUMUS', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'KELURAHAN LEMPAKE', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'KELURAHAN LOA BAKUNG', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'KELURAHAN LOA BUAH', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'KELURAHAN LOK BAHU', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'KELURAHAN MAKROMAN', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'KELURAHAN MANGKUPALAS', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'KELURAHAN MESJID', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'KELURAHAN MUGIREJO', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'KELURAHAN PASAR PAGI', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'KELURAHAN PELABUHAN', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'KELURAHAN PELITA', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'KELURAHAN PULAU ATAS', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'KELURAHAN RAPAK DALAM', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'KELURAHAN RAWA MAKMUR', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'KELURAHAN SAMBUTAN', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'KELURAHAN SELILI', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'KELURAHAN SEMPAJA BARAT', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'KELURAHAN SEMPAJA SELATAN', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'KELURAHAN SEMPAJA TIMUR', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'KELURAHAN SEMPAJA UTARA', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'KELURAHAN SENGKOTEK', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'KELURAHAN SIDODADI', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'KELURAHAN SIDODAMAI', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'KELURAHAN SIDOMULYO', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'KELURAHAN SIMPANG PASIR', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'KELURAHAN SIMPANG TIGA', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'KELURAHAN SINDANG SARI', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'KELURAHAN SUNGAI KAPIH', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'KELURAHAN SUNGAI KELEDANG', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'KELURAHAN SUNGAI PINANG DALAM', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'KELURAHAN SUNGAI PINANG LUAR', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'KELURAHAN SUNGAI SIRING', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'KELURAHAN TANAH MERAH', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'KELURAHAN TANI AMAN', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'KELURAHAN TELUK LERONG ILIR', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'KELURAHAN TELUK LERONG ULU', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'KELURAHAN TEMINDUNG PERMAI', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'KELURAHAN TENUN SAMARINDA', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'KEMENTERIAN AGAMA KOTA SAMARINDA', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'Kelurahan Bukit Pinang', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'Kelurahan Sungai Dama', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'PEMBERDAYAAN DAN KESEJAHTERAAN KELUARGA', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'PUSKEMAS BENGKURING', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'PUSKEMAS HARAPAN BARU', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'Pimpinan Utama', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'RSUD I.A MOEIS', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'RSUD IA MOEIS', 'singkatan' => 'RSUD', 'is_active' => true],
            ['nama' => 'SATUAN POLISI PAMONG PRAJA', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'SEKRETARIAT DAERAH KOTA SAMARINDA', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'SEKRETARIAT DPRD', 'singkatan' => 'SEKWAN', 'is_active' => true],
            ['nama' => 'TIM PENGGERAK PEMBERDAYAAN DAN KESEJAHTERAAN KELUARGA', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'TIM WALI KOTA UNTUK AKSELERASI PEMBANGUNAN', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'UPT Ps. Segiri', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'UPTD Laboratorium Kesehatan Daerah', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'UPTD PUSKESMAS AIR PUTIH', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'UPTD PUSKESMAS BANTUAS', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'UPTD PUSKESMAS BUKUAN', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'UPTD PUSKESMAS JUANDA', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'UPTD PUSKESMAS KAMPUNG BAQA', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'UPTD PUSKESMAS KARANG ASAM', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'UPTD PUSKESMAS LEMPAKE', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'UPTD PUSKESMAS LOA BAKUNG', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'UPTD PUSKESMAS LOK BAHU', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'UPTD PUSKESMAS MAKROMAN', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'UPTD PUSKESMAS MANGKUPALAS', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'UPTD PUSKESMAS PALARAN', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'UPTD PUSKESMAS PASUNDAN', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'UPTD PUSKESMAS REMAJA', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'UPTD PUSKESMAS SAMARINDA KOTA', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'UPTD PUSKESMAS SAMBUTAN', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'UPTD PUSKESMAS SEGIRI', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'UPTD PUSKESMAS SEMPAJA', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'UPTD PUSKESMAS SIDOMULYO', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'UPTD PUSKESMAS SUNGAI KAPIH', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'UPTD PUSKESMAS SUNGAI SIRING', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'UPTD PUSKESMAS TEMINDUNG', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'UPTD PUSKESMAS TRAUMA CENTER', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'UPTD PUSKESMAS WONOREJO', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'UPTD. Instalasi Farmasi Kota Samarinda', 'singkatan' => null, 'is_active' => true],
            ['nama' => 'WALI KOTA SAMARINDA', 'singkatan' => 'WALIKOTA', 'is_active' => true],
        ];

        $now = now();
        foreach ($opds as $opd) {
            $exists = DB::table('opd')->where('nama', $opd['nama'])->exists();
            if (!$exists) {
                DB::table('opd')->insert(array_merge($opd, [
                    'created_at' => $now,
                    'updated_at' => $now,
                ]));
            }
        }

        $this->command->info('Seeded ' . count($opds) . ' OPD records.');
    }
}
